using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace MappingGenerator;

internal static class AddAttributesSourceCode
{
    internal static void Run(IncrementalGeneratorInitializationContext incrementalGeneratorInitializationContext)
    {
        string filename = $"{CodeGenerator.MapperAttributeName}Attribute.g.cs";
        string code =
@$"// <auto-generated>
//     This code was automatically generated.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable
namespace {CodeGenerator.Namespace};

/// <summary>
/// Instructs the source generator to create mapping code from the specified source type to the decorated class. 
/// Properties with matching names are mapped implicitly.
/// </summary>
/// <param name=""sourceType"">The <see cref=""Type""/> of the source object. Using the <c>typeof</c> operator is recommended.</param>
[AttributeUsage(AttributeTargets.Class)]
public class {CodeGenerator.MapperAttributeName}Attribute(Type sourceType) : Attribute 
{{ 
    public Type SourceType {{ get; }} = sourceType; 
}}

/// <summary>
/// Explicitly defines the source property to map from, overriding the default implicit name-based mapping.
/// </summary>
/// <param name=""name"">The exact name of the source property. Using the <c>nameof</c> operator is recommended.</param>
[AttributeUsage(AttributeTargets.Property)]
public class {CodeGenerator.PropertyAttributeName}Attribute(string name) : Attribute 
{{ 
    public string Name {{ get; }} = name; 
}}

/// <summary>
/// Assigns a fixed, constant value to the decorated property during mapping, ignoring any values from the source object.
/// </summary>
/// <param name=""value"">The constant value to assign.</param>
[AttributeUsage(AttributeTargets.Property)]
public class {CodeGenerator.ValueProviderAttributeName}Attribute(object? value) : Attribute
{{
    public object? Value {{ get; }} = value;
}}

/// <summary>
/// Assigns the original value to the decorated property during mapping, ignoring any values from the source object.
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class {CodeGenerator.DefaultValueProviderAttributeName}Attribute() : Attribute {{ }}

/// <summary>
/// Injects a custom C# expression for the decorated property during code generation. 
/// The instance of the source type can be accessed via the <c>source</c> variable.
/// </summary>
/// <param name=""rawValue"">The raw C# expression to evaluate and assign (e.g., <c>""source.Value * 2""</c>).</param>
[AttributeUsage(AttributeTargets.Property)]
public class {CodeGenerator.RawValueProviderAttributeName}Attribute(string rawValue) : Attribute 
{{ 
    public string RawValue {{ get; }} = rawValue;
}}
";

        incrementalGeneratorInitializationContext.RegisterPostInitializationOutput(callback =>
        {
            callback.AddSource(filename, SourceText.From(code, Encoding.UTF8));
        });
    }
}
