using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace MappingGenerator;

internal static class AddInterfaceSourceCode
{
    internal static void Run(IncrementalGeneratorInitializationContext incrementalGeneratorInitializationContext)
    {
        string filename = "IMappable.g.cs";
        string code =
$@"// <auto-generated>
//     This code was automatically generated.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace {CodeGenerator.Namespace};

public interface {CodeGenerator.InterfaceName}<TSource, TTarget> where TSource : class where TTarget : class
{{
    static abstract TTarget MapFrom(TSource source);
    static abstract TTarget[] MapFrom(TSource[] sources);
    static abstract List<TTarget> MapFrom(List<TSource> sources);
    static abstract IEnumerable<TTarget> MapFrom(IEnumerable<TSource> sources);
    static abstract Dictionary<TKey, TTarget> MapFrom<TKey>(Dictionary<TKey, TSource> sources) where TKey : notnull;
}}
";

        incrementalGeneratorInitializationContext.RegisterPostInitializationOutput(callback =>
        {
            callback.AddSource(filename, SourceText.From(code, Encoding.UTF8));
        });
    }
}
