using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace MappingGenerator;

internal static class GeneratePartialClassSourceCode
{
    internal static void Run(SourceProductionContext sourceProductionContext, List<ClassModel> classes)
    {
        foreach (ClassModel classModel in classes)
        {
            string sourceCode = GenerateSourceCode(classModel, sourceProductionContext);
            sourceProductionContext.AddSource($"Map{classModel.SourceName}To{classModel.TargetName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }

    private static string GenerateSourceCode(ClassModel classModel, SourceProductionContext sourceProductionContext)
    {
        HashSet<string> namespaceStrings = [classModel.SourceNamespaceString, classModel.TargetNamespaceString, CodeGenerator.Namespace];
        string declaration = classModel.ClassDeclarationType switch
        {
            ClassDeclarationTypes.Class => "class",
            ClassDeclarationTypes.Record => "record",
            _ => throw new InvalidOperationException("Undefined declaration")
        };

        foreach (IPropertySymbol propertySymbol in classModel.SourceProperties.Concat(classModel.TargetProperties))
        {
            namespaceStrings.Add(propertySymbol.Type.ContainingNamespace.ToDisplayString());
        }

        return
@$"// <auto-generated>
//     This code was automatically generated.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

{string.Join("\r\n", namespaceStrings.OrderBy(namespaceString => namespaceString).Select(n => $"using {n};"))}

namespace {classModel.TargetNamespaceString};

partial {declaration} {classModel.TargetName} : {CodeGenerator.InterfaceName}<{classModel.SourceName}, {classModel.TargetName}>
{{
    /// <summary>
    /// Maps a single instance of <see cref=""{classModel.SourceName}""/> to a new instance of <see cref=""{classModel.TargetName}""/>.
    /// </summary>
    /// <param name=""source"">The source object to map from.</param>
    /// <returns>A new mapped instance of <see cref=""{classModel.TargetName}""/>.</returns>
    public static {classModel.TargetName} MapFrom({classModel.SourceName} source)
    {{
        return new {classModel.TargetName}
        {{
{GeneratePropertyMappings(classModel, sourceProductionContext)}
        }};
    }}

    /// <summary>
    /// Maps an array of <see cref=""{classModel.SourceName}""/> instances to an array of <see cref=""{classModel.TargetName}""/> instances.
    /// </summary>
    /// <param name=""sources"">The source array to map from.</param>
    /// <returns>A new array containing the mapped instances of <see cref=""{classModel.TargetName}""/>.</returns>
    public static {classModel.TargetName}[] MapFrom({classModel.SourceName}[] sources)
    {{
        {classModel.TargetName}[] targets = new {classModel.TargetName}[sources.Length];

        for (int i = 0; i < sources.Length; i++)
        {{
            targets[i] = MapFrom(sources[i]);
        }}

        return targets;
    }}

    /// <summary>
    /// Maps a list of <see cref=""{classModel.SourceName}""/> instances to a list of <see cref=""{classModel.TargetName}""/> instances.
    /// </summary>
    /// <param name=""sources"">The source list to map from.</param>
    /// <returns>A new list containing the mapped instances of <see cref=""{classModel.TargetName}""/>.</returns>
    public static List<{classModel.TargetName}> MapFrom(List<{classModel.SourceName}> sources)
    {{
        List<{classModel.TargetName}> targets = new List<{classModel.TargetName}>(sources.Count);

        for (int i = 0; i < sources.Count; i++)
        {{
            targets.Add(MapFrom(sources[i]));
        }}

        return targets;
    }}

    /// <summary>
    /// Maps a collection of <see cref=""{classModel.SourceName}""/> instances to a collection of <see cref=""{classModel.TargetName}""/> instances.
    /// </summary>
    /// <param name=""sources"">The source collection to map from.</param>
    /// <returns>A new collection containing the mapped instances of <see cref=""{classModel.TargetName}""/>.</returns>
    public static IEnumerable<{classModel.TargetName}> MapFrom(IEnumerable<{classModel.SourceName}> sources)
    {{
        return sources.Select(source => MapFrom(source));
    }}

    /// <summary>
    /// Maps a dictionary of <see cref=""{classModel.SourceName}""/> instances to a dictionary of <see cref=""{classModel.TargetName}""/> instances.
    /// </summary>
    /// <param name=""sources"">The source dictionary to map from.</param>
    /// <typeparam name=""TKey"">The source key type of the dictionary.</typeparam>
    /// <returns>A new dictionary containing the mapped instances of <see cref=""{classModel.TargetName}""/>.</returns>
    public static Dictionary<TKey, {classModel.TargetName}> MapFrom<TKey>(Dictionary<TKey, {classModel.SourceName}> sources) where TKey : notnull
    {{
        Dictionary<TKey, {classModel.TargetName}> targets = new Dictionary<TKey, {classModel.TargetName}>(sources.Count);

        foreach ((TKey key, {classModel.SourceName} source) in sources)
        {{
            targets.Add(key, MapFrom(source));
        }}

        return targets;
    }}
}}
";
    }

    private static string GeneratePropertyMappings(ClassModel classModel, SourceProductionContext sourceProductionContext)
    {
        StringBuilder sourceCode = new();

        foreach (IPropertySymbol targetProperty in classModel.TargetProperties)
        {
            AttributeData? propertyAttribute = targetProperty
                .GetAttributes()
                .FirstOrDefault(attribute =>
                    (
                        attribute.AttributeClass?.Name == CodeGenerator.PropertyAttributeName
                        || attribute.AttributeClass?.Name == $"{CodeGenerator.PropertyAttributeName}Attribute"
                    )
                    && attribute.ConstructorArguments.Length == 1
                );

            AttributeData? valueProviderAttribute = targetProperty
                .GetAttributes()
                .FirstOrDefault(attribute =>
                    (
                        attribute.AttributeClass?.Name == CodeGenerator.ValueProviderAttributeName
                        || attribute.AttributeClass?.Name == $"{CodeGenerator.ValueProviderAttributeName}Attribute"
                    )
                    && attribute.ConstructorArguments.Length == 1
                );

            AttributeData? rawValueProviderAttribute = targetProperty
                .GetAttributes()
                .FirstOrDefault(attribute =>
                    (
                        attribute.AttributeClass?.Name == CodeGenerator.RawValueProviderAttributeName
                        || attribute.AttributeClass?.Name == $"{CodeGenerator.RawValueProviderAttributeName}Attribute"
                    )
                    && attribute.ConstructorArguments.Length == 1
                );

            AttributeData? defaultValueProviderAttribute = targetProperty
                .GetAttributes()
                .FirstOrDefault(attribute => (
                    attribute.AttributeClass?.Name == CodeGenerator.DefaultValueProviderAttributeName
                    || attribute.AttributeClass?.Name == $"{CodeGenerator.DefaultValueProviderAttributeName}Attribute"
                ));

            if (rawValueProviderAttribute is not null)
            {
                sourceCode.AppendLine($"            {targetProperty.Name} = {rawValueProviderAttribute.ConstructorArguments[0].Value},");
                continue;
            }

            if (valueProviderAttribute is not null)
            {
                if (SymbolEqualityComparer.Default.Equals(targetProperty.Type, valueProviderAttribute.ConstructorArguments[0].Type))
                {
                    sourceCode.AppendLine($"            {targetProperty.Name} = {valueProviderAttribute.ConstructorArguments[0].ToCSharpString()},");
                    continue;
                }

                sourceCode.AppendLine($"            {targetProperty.Name} = {GetDefaultPropertyValue.Run(targetProperty)},");
                Location typeMismatchLocation = targetProperty.Locations.FirstOrDefault() ?? Location.None;
                Diagnostic typeMismatchDiagnostic = Diagnostic.Create(CodeGenerator.TypeMismatch, typeMismatchLocation, valueProviderAttribute.ConstructorArguments[0].Type?.Name ?? "null", classModel.SourceName, valueProviderAttribute.ConstructorArguments[0].Type?.Name ?? "null", targetProperty.Type.Name, classModel.TargetName, targetProperty.Name);
                sourceProductionContext.ReportDiagnostic(typeMismatchDiagnostic);
                continue;
            }

            if (propertyAttribute is not null)
            {
                sourceCode.AppendLine($"            {targetProperty.Name} = source.{propertyAttribute.ConstructorArguments[0].Value},");
                continue;
            }

            if (classModel.SourceProperties.FirstOrDefault(sourceProperty => sourceProperty.Name == targetProperty.Name) is IPropertySymbol sourceProperty)
            {
                if (SymbolEqualityComparer.Default.Equals(targetProperty.Type, sourceProperty.Type))
                {
                    sourceCode.AppendLine($"            {targetProperty.Name} = source.{sourceProperty.Name},");
                    continue;
                }

                sourceCode.AppendLine($"            {targetProperty.Name} = {GetDefaultPropertyValue.Run(targetProperty)},");
                Location typeMismatchLocation = targetProperty.Locations.FirstOrDefault() ?? Location.None;
                Diagnostic typeMismatchDiagnostic = Diagnostic.Create(CodeGenerator.TypeMismatch, typeMismatchLocation, sourceProperty.Type.Name, classModel.SourceName, sourceProperty.Name, targetProperty.Type.Name, classModel.TargetName, targetProperty.Name);
                sourceProductionContext.ReportDiagnostic(typeMismatchDiagnostic);
                continue;
            }

            string defaultValue = GetDefaultPropertyValue.Run(targetProperty);
            sourceCode.AppendLine($"            {targetProperty.Name} = {defaultValue},");

            if (defaultValue == "default" || defaultValueProviderAttribute is null)
            {
                Location unmappedPropertyLocation = targetProperty.Locations.FirstOrDefault() ?? Location.None;
                Diagnostic unmappedPropertyDiagnostic = Diagnostic.Create(targetProperty.IsRequired && defaultValue == "default" ? CodeGenerator.UnmappedRequiredProperty : CodeGenerator.UnmappedProperty, unmappedPropertyLocation, CodeGenerator.PropertyAttributeName, CodeGenerator.ValueProviderAttributeName, CodeGenerator.RawValueProviderAttributeName);
                sourceProductionContext.ReportDiagnostic(unmappedPropertyDiagnostic);
            }
        }

        return sourceCode.ToString().TrimEnd('\r', '\n', ',');
    }
}
