using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace MappingGenerator;

internal static class GeneratePartialClassSourceCode
{
    internal static void Run(SourceProductionContext sourceProductionContext, List<ClassModel> classes)
    {
        foreach (ClassModel classModel in classes)
        {
            string sourceCode = GenerateSourceCode(classModel, sourceProductionContext);
            sourceProductionContext.AddSource($"Map{classModel.SourceName}To{classModel.TargetName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
        }
    }

    private static string GenerateSourceCode(ClassModel classModel, SourceProductionContext sourceProductionContext)
    {
        HashSet<string> namespaceStrings = [classModel.SourceNamespaceString, classModel.TargetNamespaceString, CodeGenerator.Namespace];
        string declaration = classModel.ClassDeclarationType switch
        {
            ClassDeclarationTypes.Class => "class",
            ClassDeclarationTypes.Record => "record",
            _ => throw new InvalidOperationException("Undefined declaration")
        };

        foreach (IPropertySymbol propertySymbol in classModel.SourceProperties.Concat(classModel.TargetProperties))
        {
            namespaceStrings.Add(propertySymbol.Type.ContainingNamespace.ToDisplayString());
        }

        StringBuilder sourceCode = new();
        sourceCode.AppendLine("// <auto-generated>");
        sourceCode.AppendLine("//     This code was automatically generated.");
        sourceCode.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
        sourceCode.AppendLine("// </auto-generated>");
        sourceCode.AppendLine();
        sourceCode.AppendLine("#nullable enable");
        sourceCode.AppendLine();
        foreach (string namespaceString in namespaceStrings.OrderBy(namespaceString => namespaceString))
        {
            sourceCode.AppendLine($"using {namespaceString};");
        }
        sourceCode.AppendLine();
        sourceCode.AppendLine($"namespace {classModel.TargetNamespaceString};");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"partial {declaration} {classModel.TargetName} : {CodeGenerator.InterfaceName}<{classModel.SourceName}, {classModel.TargetName}>");
        sourceCode.AppendLine($"{{");
        sourceCode.AppendLine($"    /// <summary>");
        sourceCode.AppendLine($"    /// Maps a single instance of <see cref=\"{classModel.SourceName}\"/> to a new instance of <see cref=\"{classModel.TargetName}\"/>.");
        sourceCode.AppendLine($"    /// </summary>");
        sourceCode.AppendLine($"    /// <param name=\"source\">The source object to map from.</param>");
        sourceCode.AppendLine($"    /// <returns>A new mapped instance of <see cref=\"{classModel.TargetName}\"/>.</returns>");
        sourceCode.AppendLine($"    public static {classModel.TargetName} MapFrom({classModel.SourceName} source)");
        sourceCode.AppendLine($"    {{");
        sourceCode.AppendLine($"        return new {classModel.TargetName}");
        sourceCode.AppendLine($"        {{");
        GeneratePropertyMappings(sourceCode, classModel, sourceProductionContext);
        sourceCode.AppendLine($"        }};");
        sourceCode.AppendLine($"    }}");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"    /// <summary>");
        sourceCode.AppendLine($"    /// Maps an array of <see cref=\"{classModel.SourceName}\"/> instances to an array of <see cref=\"{classModel.TargetName}\"/> instances.");
        sourceCode.AppendLine($"    /// </summary>");
        sourceCode.AppendLine($"    /// <param name=\"sources\">The source array to map from.</param>");
        sourceCode.AppendLine($"    /// <returns>A new array containing the mapped instances of <see cref=\"{classModel.TargetName}\"/>.</returns>");
        sourceCode.AppendLine($"    public static {classModel.TargetName}[] MapFrom({classModel.SourceName}[] sources)");
        sourceCode.AppendLine($"    {{");
        sourceCode.AppendLine($"        {classModel.TargetName}[] targets = new {classModel.TargetName}[sources.Length];");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"        for (int i = 0; i < sources.Length; i++)");
        sourceCode.AppendLine($"        {{");
        sourceCode.AppendLine($"            targets[i] = MapFrom(sources[i]);");
        sourceCode.AppendLine($"        }}");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"        return targets;");
        sourceCode.AppendLine($"    }}");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"    /// <summary>");
        sourceCode.AppendLine($"    /// Maps a list of <see cref=\"{classModel.SourceName}\"/> instances to a list of <see cref=\"{classModel.TargetName}\"/> instances.");
        sourceCode.AppendLine($"    /// </summary>");
        sourceCode.AppendLine($"    /// <param name=\"sources\">The source list to map from.</param>");
        sourceCode.AppendLine($"    /// <returns>A new list containing the mapped instances of <see cref=\"{classModel.TargetName}\"/>.</returns>");
        sourceCode.AppendLine($"    public static List<{classModel.TargetName}> MapFrom(List<{classModel.SourceName}> sources)");
        sourceCode.AppendLine($"    {{");
        sourceCode.AppendLine($"        List<{classModel.TargetName}> targets = new List<{classModel.TargetName}>(sources.Count);");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"        for (int i = 0; i < sources.Count; i++)");
        sourceCode.AppendLine($"        {{");
        sourceCode.AppendLine($"            targets.Add(MapFrom(sources[i]));");
        sourceCode.AppendLine($"        }}");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"        return targets;");
        sourceCode.AppendLine($"    }}");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"    /// <summary>");
        sourceCode.AppendLine($"    /// Maps a collection of <see cref=\"{classModel.SourceName}\"/> instances to a collection of <see cref=\"{classModel.TargetName}\"/> instances.");
        sourceCode.AppendLine($"    /// </summary>");
        sourceCode.AppendLine($"    /// <param name=\"sources\">The source collection to map from.</param>");
        sourceCode.AppendLine($"    /// <returns>A new collection containing the mapped instances of <see cref=\"{classModel.TargetName}\"/>.</returns>");
        sourceCode.AppendLine($"    public static IEnumerable<{classModel.TargetName}> MapFrom(IEnumerable<{classModel.SourceName}> sources)");
        sourceCode.AppendLine($"    {{");
        sourceCode.AppendLine($"        return sources.Select(source => MapFrom(source));");
        sourceCode.AppendLine($"    }}");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"    /// <summary>");
        sourceCode.AppendLine($"    /// Maps a dictionary of <see cref=\"{classModel.SourceName}\"/> instances to a dictionary of <see cref=\"{classModel.TargetName}\"/> instances.");
        sourceCode.AppendLine($"    /// </summary>");
        sourceCode.AppendLine($"    /// <param name=\"sources\">The source dictionary to map from.</param>");
        sourceCode.AppendLine($"    /// <typeparam name=\"TKey\">The source key type of the dictionary.</typeparam>");
        sourceCode.AppendLine($"    /// <returns>A new dictionary containing the mapped instances of <see cref=\"{classModel.TargetName}\"/>.</returns>");
        sourceCode.AppendLine($"    public static Dictionary<TKey, {classModel.TargetName}> MapFrom<TKey>(Dictionary<TKey, {classModel.SourceName}> sources) where TKey : notnull");
        sourceCode.AppendLine($"    {{");
        sourceCode.AppendLine($"        Dictionary<TKey, {classModel.TargetName}> targets = new Dictionary<TKey, {classModel.TargetName}>(sources.Count);");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"        foreach ((TKey key, {classModel.SourceName} source) in sources)");
        sourceCode.AppendLine($"        {{");
        sourceCode.AppendLine($"            targets.Add(key, MapFrom(source));");
        sourceCode.AppendLine($"        }}");
        sourceCode.AppendLine();
        sourceCode.AppendLine($"        return targets;");
        sourceCode.AppendLine($"    }}");
        sourceCode.AppendLine($"}}");
        return sourceCode.ToString();
    }

    private static void GeneratePropertyMappings(StringBuilder sourceCode, ClassModel classModel, SourceProductionContext sourceProductionContext)
    {
        foreach (IPropertySymbol targetProperty in classModel.TargetProperties)
        {
            AttributeData? propertyAttribute = targetProperty
                .GetAttributes()
                .FirstOrDefault(attribute =>
                    (
                        attribute.AttributeClass?.Name == CodeGenerator.PropertyAttributeName
                        || attribute.AttributeClass?.Name == $"{CodeGenerator.PropertyAttributeName}Attribute"
                    )
                    && attribute.ConstructorArguments.Length == 1
                );

            AttributeData? valueProviderAttribute = targetProperty
                .GetAttributes()
                .FirstOrDefault(attribute =>
                    (
                        attribute.AttributeClass?.Name == CodeGenerator.ValueProviderAttributeName
                        || attribute.AttributeClass?.Name == $"{CodeGenerator.ValueProviderAttributeName}Attribute"
                    )
                    && attribute.ConstructorArguments.Length == 1
                );

            AttributeData? rawValueProviderAttribute = targetProperty
                .GetAttributes()
                .FirstOrDefault(attribute =>
                    (
                        attribute.AttributeClass?.Name == CodeGenerator.RawValueProviderAttributeName
                        || attribute.AttributeClass?.Name == $"{CodeGenerator.RawValueProviderAttributeName}Attribute"
                    )
                    && attribute.ConstructorArguments.Length == 1
                );

            if (rawValueProviderAttribute is not null)
            {
                sourceCode.AppendLine($"            {targetProperty.Name} = {rawValueProviderAttribute.ConstructorArguments[0].Value},");
                continue;
            }

            if (valueProviderAttribute is not null)
            {
                if (SymbolEqualityComparer.Default.Equals(targetProperty.Type, valueProviderAttribute.ConstructorArguments[0].Type))
                {
                    sourceCode.AppendLine($"            {targetProperty.Name} = {valueProviderAttribute.ConstructorArguments[0].ToCSharpString()},");
                    continue;
                }

                sourceCode.AppendLine($"            {targetProperty.Name} = default,");
                Location location = targetProperty.Locations.FirstOrDefault() ?? Location.None;
                Diagnostic diagnostic = Diagnostic.Create(CodeGenerator.PropertyTypeMismatch, location, valueProviderAttribute.ConstructorArguments[0].Type?.Name ?? "null", classModel.SourceName, valueProviderAttribute.ConstructorArguments[0].Type?.Name ?? "null", targetProperty.Type.Name, classModel.TargetName, targetProperty.Name);
                sourceProductionContext.ReportDiagnostic(diagnostic);
                continue;
            }

            if (propertyAttribute is not null)
            {
                sourceCode.AppendLine($"            {targetProperty.Name} = source.{propertyAttribute.ConstructorArguments[0].Value},");
                continue;
            }

            if (classModel.SourceProperties.FirstOrDefault(sourceProperty => sourceProperty.Name == targetProperty.Name) is IPropertySymbol sourceProperty)
            {
                if (SymbolEqualityComparer.Default.Equals(targetProperty.Type, sourceProperty.Type))
                {
                    sourceCode.AppendLine($"            {targetProperty.Name} = source.{sourceProperty.Name},");
                    continue;
                }

                sourceCode.AppendLine($"            {targetProperty.Name} = default,");
                Location location = targetProperty.Locations.FirstOrDefault() ?? Location.None;
                Diagnostic diagnostic = Diagnostic.Create(CodeGenerator.PropertyTypeMismatch, location, sourceProperty.Type.Name, classModel.SourceName, sourceProperty.Name, targetProperty.Type.Name, classModel.TargetName, targetProperty.Name);
                sourceProductionContext.ReportDiagnostic(diagnostic);
                continue;
            }
            
            if (targetProperty.IsRequired)
            {
                sourceCode.AppendLine($"            {targetProperty.Name} = default,");

                Location location = targetProperty.Locations.FirstOrDefault() ?? Location.None;
                Diagnostic diagnostic = Diagnostic.Create(CodeGenerator.UnmappedRequiredPropertyWarning, location, CodeGenerator.PropertyAttributeName, CodeGenerator.ValueProviderAttributeName, CodeGenerator.RawValueProviderAttributeName);
                sourceProductionContext.ReportDiagnostic(diagnostic);
            }
        }
    }
}
